[package]
name = "ghost-fl-workspace"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
ghost-audio = { path = "../../crates/ghost-audio" }
ghost-codex = { path = "../../crates/ghost-codex" }
ghost-fl-scripting = { path = "../../crates/ghost-fl-scripting" }
ghost-fl-studio = { path = "../../crates/ghost-fl-studio" }
ghost-tap = { path = "../../crates/ghost-tap" }
serde.workspace = true
serde_json.workspace = true
