// Generated by `cargo xtask bindings`; do not edit by hand.
export type RuntimePhase = "booting" | "discovering_fl" | "waiting_fl_ui" | "waiting_gopher" | "opening_gopher" | "starting_app" | "waiting_app" | "waiting_scripting" | "ready" | "degraded" | "failed" | "stopping" | "stopped";

export type FlState = { pid: number | null, launchedByGhost: boolean, windowReady: boolean, debugPort: number, gopherReady: boolean, gopherTarget: string | null, gopherToolCount: number | null, };

export type AppState = { profile: string, pid: number | null, endpoint: string, healthy: boolean, scriptingConnected: boolean | null, threadId: string | null, lastError: string | null, };

export type RuntimeState = { sessionId: string, phase: RuntimePhase, startedAtUnixMs: number, updatedAtUnixMs: number, fl: FlState, app: AppState, lastError: string | null, };

export type RuntimeEvent = { sequence: number, timestampUnixMs: number, component: string, event: string, severity: string, data: unknown, };

export type RegisteredApp = { id: string, displayName: string, route: string, uiUrl: string, endpoint: string, healthy: boolean, };

export type SocketMessage =
	| { kind: 'snapshot'; state: RuntimeState; events: RuntimeEvent[] }
	| { kind: 'event'; state: RuntimeState; event: RuntimeEvent };
