[package]
name = "analyse-full"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
ghost-audio = { path = "../../crates/ghost-audio" }
ghost-tap = { path = "../../crates/ghost-tap" }
serde_json.workspace = true
