[package]
name = "ghost-host"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true
rust-version.workspace = true

[features]
default = []
clack-runtime = ["dep:clack-host", "dep:clack-extensions"]

[dependencies]
crossbeam-queue.workspace = true
clack-host = { workspace = true, optional = true }
clack-extensions = { workspace = true, optional = true, features = ["audio-ports", "clack-host", "gui", "latency", "log", "params", "state", "thread-check", "timer"] }
ghost-core = { path = "../ghost-core" }
ghost-mix = { path = "../ghost-mix" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
