[package]
name = "ghost-clap-plugin"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
clack-extensions = { workspace = true, features = ["audio-ports", "clack-plugin", "gui", "latency", "params", "raw-window-handle_06", "state"] }
clack-plugin.workspace = true
clack-common.workspace = true
egui.workspace = true
egui-baseview.workspace = true
ghost-core = { path = "../ghost-core" }
ghost-host = { path = "../ghost-host", features = ["clack-runtime"] }
ghost-ui = { path = "../ghost-ui" }
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
